In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Loading the cleaned data after preprocessing.
df = pd.read_csv("C:/Users/KRISHNA/Desktop/SHWETA/Fall 2024/Project/Cleaned_Loan_approval_dataset.csv")

In [4]:
df.head()

,LoanNumber,UserName,NewCreditCustomer,VerificationType,LanguageCode,Age,Gender,Country,AppliedAmount,Amount,...,CreditScoreEsMicroL,CreditScoreEeMini,PrincipalPaymentsMade,InterestAndPenaltyPaymentsMade,PrincipalBalance,InterestAndPenaltyBalance,NoOfPreviousLoansBeforeLoan,AmountOfPreviousLoansBeforeLoan,PreviousRepaymentsBeforeLoan,PreviousEarlyRepaymentsCountBeforeLoan
0,483449,BO965519,Existing_credit_customer,Income_expenses_verified,1,53,Female,EE,2125.0,2125.0,...,M,1000.0,969.16,1187.91,1155.84,433.60,1.0,500.0,590.95,0.0
1,378148,BOA9K172A,Existing_credit_customer,Income_unverified,1,50,Female,EE,3000.0,3000.0,...,M,1000.0,563.59,360.07,2436.41,2291.82,1.0,1800.0,445.26,1.0
2,451831,BO7971663,New_credit_Customer,Income_expenses_verified,1,44,Male,EE,10630.0,9100.0,...,M,1000.0,6537.00,1708.47,0.00,0.00,0.0,0.0,0.00,0.0
3,349381,BO76151K3,New_credit_Customer,Income_verified,6,42,Male,ES,1500.0,1500.0,...,M3,1000.0,464.73,355.92,1035.27,2833.83,0.0,0.0,0.00,1.0
4,443082,BOK423A63,New_credit_Customer,Income_expenses_verified,6,34,Female,ES,1595.0,1090.0,...,M5,1000.0,0.01,0.00,1089.99,4215.37,0.0,0.0,0.00,0.0